[build]
  command = "./build.sh"
  functions = "functions"
  publish = "public"

[build.environment]
  GO_IMPORT_PATH = "https://github.com/Anslem1/taskforhng"
  GO111MODULE = "on"


  [[redirects]]
  from = "/main.go"
  to = "/.netlify/functions/gateway/:splat"
  status = 200